CREATE TABLE events (
                        id SERIAL PRIMARY KEY,
                        title VARCHAR(150) NOT NULL,
                        description TEXT NOT NULL,
                        date DATE NOT NULL,
                        start_time TIME NOT NULL,
                        duration_minutes INTEGER NOT NULL,
                        location VARCHAR(150) NOT NULL,
                        image VARCHAR(255) NOT NULL
);

INSERT INTO events (title, description, date, start_time, duration_minutes, location, image)
VALUES
    (
        'Meet the Vet',
        'An interactive lecture for kids about animal health in the zoo.',
        '2025-06-30',
        '11:00:00',
        90,
        'Conference Hall #1',
        'veterinary_event.jpg'
    ),
    (
        'Night at the Zoo',
        'A night tour with flashlights, learning about nocturnal animals.',
        '2025-07-15',
        '21:00:00',
        120,
        'Main Entrance',
        'night_zoo_tour.jpg'
    ),
    (
        'Open Day',
        'Free admission for all visitors and special activities throughout the zoo.',
        '2025-08-01',
        '09:00:00',
        480,
        'Entire Zoo Area',
        'open_day_banner.jpg'
    ),
    ('World Giraffe Day',
     'Celebrate and learn about giraffes with fun facts and feeding sessions.',
     '2025-06-21',
     '10:00:00',
     120,
     'Giraffe Enclosure',
     'giraffe_day.jpg'),

    ('Bird Show Extravaganza',
     'Live bird demonstrations featuring parrots, owls, and falcons.',
     '2025-07-05',
     '14:00:00',
     60,
     'Bird Arena',
     'bird_show.jpg'),

    ('Zoo Anniversary Celebration',
     'Marking the 10th anniversary with a parade and special events.',
     '2025-07-20',
     '12:00:00',
     300,
     'Main Stage',
     'zoo_anniversary.jpg'),

    ('Dinosaur Discovery Day',
     'Educational event for kids about prehistoric animals.',
     '2025-07-10',
     '13:00:00',
     90,
     'Paleo Zone',
     'dinosaur_day.jpg'),

    ('Keeper Talk: Elephants',
     'Join our elephant keepers to learn about care and behavior.',
     '2025-06-25',
     '15:00:00',
     45,
     'Elephant Habitat',
     'elephant_talk.jpg'),

    ('Butterfly Garden Opening',
     'Grand opening of our new butterfly pavilion.',
     '2025-08-10',
     '10:30:00',
     60,
     'Butterfly Garden',
     'butterfly_opening.jpg'),

    ('Penguin Feeding Experience',
     'Watch and learn how penguins are fed and cared for.',
     '2025-06-29',
     '12:00:00',
     30,
     'Penguin Pool',
     'penguin_feeding.jpg'),

    ('Summer Kids Festival',
     'Games, contests, and shows for kids throughout the zoo.',
     '2025-07-12',
     '10:00:00',
     360,
     'Children Zone',
     'summer_kids_festival.jpg'),

    ('Eco Awareness Week',
     'Daily talks and activities on conservation and sustainability.',
     '2025-08-05',
     '09:30:00',
     420,
     'Eco Pavilion',
     'eco_awareness.jpg'),

    ('Zoo by Candlelight',
     'A relaxed evening with soft lighting and acoustic music.',
     '2025-08-14',
     '20:00:00',
     150,
     'Botanical Garden',
     'zoo_candlelight.jpg'),

    ('Art in the Zoo',
     'Live painting and photography sessions inspired by animals.',
     '2025-06-28',
     '11:00:00',
     180,
     'Central Lawn',
     'art_in_zoo.jpg'),

    ('Volunteer Appreciation Day',
     'Honoring our amazing zoo volunteers with a picnic and awards.',
     '2025-07-22',
     '13:00:00',
     120,
     'Picnic Area',
     'volunteer_day.jpg');

